Numpy Questions

In [1]:
import numpy as np

Q1

In [3]:
A = np.array([1, 5, 7, 9, 10, 3, 2, 5, 8, 9])
B = np.array([5, 8, 2, 8,  1, 3, 10, 2, 3, 6])

v_stacked = np.vstack([A, B])
h_stacked = np.hstack([A, B])

print(v_stacked)
print(h_stacked)

[[ 1  5  7  9 10  3  2  5  8  9]
 [ 5  8  2  8  1  3 10  2  3  6]]
[ 1  5  7  9 10  3  2  5  8  9  5  8  2  8  1  3 10  2  3  6]


Q2

In [5]:
common = np.intersect1d(A, B)
print(common)

[ 1  2  3  5  8 10]


Q3

In [7]:
mask = (A >= 5) & (A <= 10)
vals_in_range = A[mask]
print(vals_in_range)

[ 5  7  9 10  5  8  9]


Q4

In [9]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_filtered = iris_2d[iris_mask]
print(iris_filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Pandas Questions

In [10]:
import pandas as pd

Q1

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
every_20th = df.loc[::20, ['Manufacturer', 'Model', 'Type']].reset_index(drop=True)

Q2

In [15]:
df2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv').copy()
for col in ['Min.Price', 'Max.Price']:
    df2[col] = df2[col].fillna(df2[col].mean())
print(df2)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

Q3

In [16]:
df_rand = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4),
                       columns=list('ABCD'))
rows_sum_gt_100 = df_rand[df_rand.sum(axis=1) > 100]
print(rows_sum_gt_100)

     A   B   C   D
0   16  37  32  31
1   34  25  23  28
3   39  37  12  36
4   25  35  31  25
8   39  21  36  35
9   36  24  11  39
14  39  34  22  11
